import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      fontFamily: {
        sans: ['Space Grotesk', 'sans-serif'],
        serif: ['Crimson Pro', 'serif'],
      },
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        emotion: {
          neutral: "hsl(var(--emotion-neutral))",
          angry: "hsl(var(--emotion-angry))",
          sad: "hsl(var(--emotion-sad))",
          happy: "hsl(var(--emotion-happy))",
          anxious: "hsl(var(--emotion-anxious))",
          fearful: "hsl(var(--emotion-fearful))",
          manic: "hsl(var(--emotion-manic))",
          confused: "hsl(var(--emotion-confused))",
          frustrated: "hsl(var(--emotion-frustrated))",
          lonely: "hsl(var(--emotion-lonely))",
          peaceful: "hsl(var(--emotion-peaceful))",
          grateful: "hsl(var(--emotion-grateful))",
          hopeful: "hsl(var(--emotion-hopeful))",
          loving: "hsl(var(--emotion-loving))",
          proud: "hsl(var(--emotion-proud))",
          excited: "hsl(var(--emotion-excited))",
          amused: "hsl(var(--emotion-amused))",
          content: "hsl(var(--emotion-content))",
          jealous: "hsl(var(--emotion-jealous))",
          guilty: "hsl(var(--emotion-guilty))",
          ashamed: "hsl(var(--emotion-ashamed))",
          disgusted: "hsl(var(--emotion-disgusted))",
          bitter: "hsl(var(--emotion-bitter))",
          resentful: "hsl(var(--emotion-resentful))",
          envious: "hsl(var(--emotion-envious))",
          nostalgic: "hsl(var(--emotion-nostalgic))",
          melancholic: "hsl(var(--emotion-melancholic))",
          contemplative: "hsl(var(--emotion-contemplative))",
          curious: "hsl(var(--emotion-curious))",
          bored: "hsl(var(--emotion-bored))",
          apathetic: "hsl(var(--emotion-apathetic))",
          ecstatic: "hsl(var(--emotion-ecstatic))",
          devastated: "hsl(var(--emotion-devastated))",
          furious: "hsl(var(--emotion-furious))",
          terrified: "hsl(var(--emotion-terrified))",
          awestruck: "hsl(var(--emotion-awestruck))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
